CREATE TABLE FORMULARIO(
id int  IDENTITY(1,1) PRIMARY KEY,
nome varchar(150),
cpf varchar(50),
email varchar(50),
telefone varchar(15),
habilitado varchar(3),
categoria varchar(20),
linguaEs varchar(50),
cep varchar(9),
estado varchar(50),
cidade varchar(50),
bairro varchar(50),
logradouro varchar(150),
end_num varchar(10),
complemento varchar(150),
cargo varchar(50),
salarioProp varchar(20),
)