
CREATE TABLE [DEPARTAMENTOS](
	[COD_DEPART] [int] NOT NULL,
	[NOME_RESP] [varchar](150) NOT NULL,
	[USUARIO_RESP] [varchar](50) NOT NULL,
	[EMAIL_RESP] [varchar](50) NOT NULL,
 CONSTRAINT [AK_TransactionID] UNIQUE NONCLUSTERED 
(
	[COD_DEPART] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]



